### ISSUE TITLE
Possible to generate random-length subarray in object template?

### ISSUE THREAD

**Issue by shauntarves** [bkumar2/random-ext#3]
Hello,

Thanks for this great library. I'm having an issue that I'm not sure is possible. I have an object template like this:

```
const foo = {
  id: randomExt.integer(100, 0)
};

const foos = randomExt.objectArray(20, foo);
```

And in another object, I want to have a random-length array of values from `foos`. I've tried like this:
```
const bar = {
  foos: randomExt.subArray(foos, randomExt.integer(3, 0))
};
```
but it doesn't seem to work as I would hope.

**Comment by bkumar2** [comment]
Hi, Thanks for writing question. Apologies for not being active on the project.

In your question, Object template is incorrect. Object template requires attribute values to be an array where first element of the array should be the function and other elements should be the arguments. So, your program would look like this:

`var randomExt = require("random-ext")
const fooObjectTemplate = {
    id: [randomExt.integer, 100, 0]
}
const foos = randomExt.objectArray(20, fooObjectTemplate);
const bar = {
  foos: randomExt.subArray(foos, randomExt.integer(3, 0))
};`

Hope this helps.
